"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Command } from "cmdk";
import * as Dialog from "@radix-ui/react-dialog";
import { track } from "@/lib/analytics";

// The heavy half of the search palette (cmdk + Radix Dialog + Pagefind
// glue). Loaded on demand by search-palette.tsx the first time the user
// opens search, so none of this ships in the shared layout bundle.

// Pagefind is generated at /pagefind/pagefind.js by the postbuild step. The
// import is dynamic + runtime so it doesn't get bundled by Next and so dev
// mode (where /pagefind/ doesn't exist) can fail gracefully.
type PagefindSubResult = {
  url: string;
  excerpt: string;
};

type PagefindResult = {
  id: string;
  data: () => Promise<{
    url: string;
    meta: { title?: string };
    excerpt: string;
    sub_results?: PagefindSubResult[];
  }>;
};

type Pagefind = {
  search: (query: string) => Promise<{ results: PagefindResult[] }>;
  destroy?: () => Promise<void>;
};

type Hit = {
  url: string;
  title: string;
  excerpt: string;
};

declare global {
  interface Window {
    __pagefind?: Pagefind;
  }
}

async function loadPagefind(): Promise<Pagefind | null> {
  if (typeof window === "undefined") return null;
  if (window.__pagefind) return window.__pagefind;
  try {
    // The Pagefind runtime is generated by the postbuild step at
    // /out/pagefind/pagefind.js. The webpackIgnore comment keeps Next from
    // bundling it; the path is resolved by the browser at runtime.
    const path = "/pagefind/pagefind.js";
    const mod = (await import(/* webpackIgnore: true */ /* @vite-ignore */ path)) as Pagefind;
    window.__pagefind = mod;
    return mod;
  } catch {
    return null;
  }
}

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

export function SearchPaletteDialog({ open, onOpenChange }: Props) {
  const [query, setQuery] = useState("");
  const [hits, setHits] = useState<Hit[]>([]);
  const [status, setStatus] = useState<
    "idle" | "loading" | "empty" | "error"
  >("idle");

  useEffect(() => {
    let cancelled = false;
    if (!query) {
      setHits([]);
      setStatus("idle");
      return;
    }
    setStatus("loading");
    (async () => {
      const pf = await loadPagefind();
      if (!pf) {
        if (!cancelled) setStatus("error");
        return;
      }
      const res = await pf.search(query);
      const top = await Promise.all(res.results.slice(0, 8).map((r) => r.data()));
      if (cancelled) return;
      const mapped: Hit[] = top.map((d) => ({
        url: d.url,
        title: d.meta?.title || prettyUrl(d.url),
        excerpt: d.excerpt.replace(/<[^>]+>/g, ""),
      }));
      setHits(mapped);
      setStatus(mapped.length === 0 ? "empty" : "idle");
    })();
    return () => {
      cancelled = true;
    };
  }, [query]);

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-50 bg-surface-tuxedo/80 backdrop-blur-sm data-[state=open]:animate-in data-[state=open]:fade-in-0 motion-reduce:data-[state=open]:animate-none" />
        <Dialog.Content
          aria-describedby={undefined}
          className="fixed left-1/2 top-[14svh] z-50 w-[min(640px,92vw)] -translate-x-1/2 border border-surface-ivory/15 bg-surface-tuxedo"
        >
          <Dialog.Title className="sr-only">Search</Dialog.Title>
          <Command
            shouldFilter={false}
            label="Search Stoned Goose Productions"
            className="flex flex-col"
          >
            <div className="flex items-center gap-3 border-b border-surface-ivory/15 px-5 py-4">
              <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent-gold">
                /
              </span>
              <Command.Input
                value={query}
                onValueChange={setQuery}
                placeholder="Search shows, comics, services..."
                className="flex-1 bg-transparent font-body text-base text-surface-ivory placeholder:text-surface-ivory/55 focus:outline-none"
                autoFocus
              />
              <span className="hidden font-mono text-[10px] uppercase tracking-[0.18em] text-surface-ivory/55 md:inline">
                ESC
              </span>
            </div>
            {/* Live region announces search progress and result counts to
                screen readers as the query changes. */}
            <div role="status" aria-live="polite" className="sr-only">
              {status === "loading"
                ? "Searching."
                : status === "empty"
                  ? "No results."
                  : status === "error"
                    ? "Search unavailable."
                    : hits.length > 0
                      ? `${hits.length} results.`
                      : ""}
            </div>
            <Command.List className="max-h-[60svh] overflow-y-auto py-2">
              {status === "loading" && (
                <p className="px-5 py-4 font-body text-sm text-surface-ivory/55">
                  Searching.
                </p>
              )}
              {status === "empty" && (
                <p className="px-5 py-4 font-body text-sm text-surface-ivory/55">
                  Nothing matches that. The map is bigger than the search box.
                </p>
              )}
              {status === "error" && (
                <p className="px-5 py-4 font-body text-sm text-surface-ivory/55">
                  Search index not built. Run a production build.
                </p>
              )}
              {hits.map((h) => (
                <Command.Item
                  key={h.url}
                  value={`${h.url}-${h.title}`}
                  onSelect={() => {
                    track("Search Result Click", { url: h.url });
                    onOpenChange(false);
                    window.location.assign(h.url);
                  }}
                  asChild
                >
                  <Link
                    href={h.url}
                    onClick={() => onOpenChange(false)}
                    className="block cursor-pointer border-l-2 border-transparent px-5 py-3 hover:border-surface-ivory hover:bg-surface-ivory/[0.04] data-[selected=true]:border-accent-gold data-[selected=true]:bg-surface-ivory/[0.04]"
                  >
                    <p className="font-display text-base text-surface-ivory md:text-lg">
                      {h.title}
                    </p>
                    <p className="mt-1 line-clamp-2 font-body text-xs text-surface-ivory/65">
                      {h.excerpt}
                    </p>
                    <p className="mt-1 font-mono text-[10px] uppercase tracking-[0.18em] text-surface-ivory/55">
                      {prettyUrl(h.url)}
                    </p>
                  </Link>
                </Command.Item>
              ))}
            </Command.List>
            <p className="border-t border-surface-ivory/15 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.18em] text-surface-ivory/55">
              ⌘K to toggle. Index rebuilds on deploy.
            </p>
          </Command>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

function prettyUrl(url: string) {
  try {
    const u = new URL(url, "https://x");
    return u.pathname.replace(/\/$/, "") || "/";
  } catch {
    return url;
  }
}
