import generated from "@/content/.generated/placeholders.json";

// Build-time LQIP map keyed by public image path. Generated by
// scripts/build-placeholders.ts during prebuild. When the entry is missing
// (ran with sync skipped, or source removed), components fall back to no
// placeholder rather than failing.
const placeholders = generated as Record<string, string>;

export function getPlaceholder(path: string): string | undefined {
  return placeholders[path];
}
