// Open mic data-quality report.
//
// Reads the raw, consolidated mic index and flags records that need a human
// pass in the CMS: missing city, unparseable time, non-URL signup links, host
// slots holding emails/URLs, and venue spellings the render layer is silently
// correcting. Writes a markdown report to the repo root so the owner has a
// punch list for cleaning the source data later.
//
// This never mutates source. It is a reporting tool, not part of the build.
//
// Run: npm run mics:quality

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { analyzeMic, type MicIssue } from "../lib/open-mics/normalize";
import type { OpenMic } from "../content/open-mics";

const ROOT = process.cwd();
const INDEX_PATH = join(ROOT, "content", ".generated", "open-mics-index.json");
const LEGACY_PATH = join(ROOT, "content", "feeds", "open-mics.json");
const REPORT_PATH = join(ROOT, "OPEN_MICS_DATA_QUALITY.md");

type RawMic = Partial<OpenMic> & Record<string, unknown>;

function loadRawMics(): RawMic[] {
  if (existsSync(INDEX_PATH)) {
    const parsed = JSON.parse(readFileSync(INDEX_PATH, "utf8"));
    if (Array.isArray(parsed) && parsed.length > 0) return parsed as RawMic[];
  }
  if (existsSync(LEGACY_PATH)) {
    const parsed = JSON.parse(readFileSync(LEGACY_PATH, "utf8"));
    if (Array.isArray(parsed?.mics)) return parsed.mics as RawMic[];
  }
  return [];
}

function toOpenMic(raw: RawMic): OpenMic {
  return {
    id: (raw.id as string) ?? "",
    name: (raw.name as string) ?? "",
    venue: (raw.venue as string) ?? "",
    address: (raw.address as string) ?? "",
    city: (raw.city as string) ?? "",
    region: (raw.region as string) ?? "",
    lat: Number(raw.lat ?? 0),
    lng: Number(raw.lng ?? 0),
    day: (raw.day as OpenMic["day"]) ?? "Monday",
    time: (raw.time as string) ?? "",
    frequency: (raw.frequency as OpenMic["frequency"]) ?? "weekly",
    host: raw.host as string | undefined,
    signupUrl: raw.signupUrl as string | undefined,
    notes: raw.notes as string | undefined,
  };
}

function main() {
  const rawMics = loadRawMics();
  if (rawMics.length === 0) {
    console.warn("[mics:quality] No mic records found. Nothing to report.");
    return;
  }

  const allIssues: MicIssue[] = [];
  for (const raw of rawMics) {
    allIssues.push(...analyzeMic(toOpenMic(raw)));
  }

  const byField = new Map<MicIssue["field"], MicIssue[]>();
  for (const issue of allIssues) {
    if (!byField.has(issue.field)) byField.set(issue.field, []);
    byField.get(issue.field)!.push(issue);
  }

  const errors = allIssues.filter((i) => i.severity === "error").length;
  const warnings = allIssues.filter((i) => i.severity === "warning").length;
  const flaggedIds = new Set(allIssues.map((i) => i.id));

  const fieldOrder: MicIssue["field"][] = [
    "city",
    "time",
    "signup",
    "host",
    "address",
    "venue",
  ];
  const fieldTitles: Record<MicIssue["field"], string> = {
    city: "Missing city",
    time: "Malformed time",
    signup: "Non-URL signup links",
    host: "Host slot holds email / URL",
    address: "Address issues",
    venue: "Venue spelling corrected on render",
  };

  const lines: string[] = [];
  lines.push("# Open mic data quality report");
  lines.push("");
  lines.push(
    "Generated by `npm run mics:quality`. This is a punch list for cleaning the",
  );
  lines.push(
    "source records in the CMS. The site already renders these cleanly via the",
  );
  lines.push(
    "normalization layer (`lib/open-mics/normalize.ts`); fixing the source just",
  );
  lines.push("removes the need for that correction.");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Records scanned: ${rawMics.length}`);
  lines.push(`- Records with at least one issue: ${flaggedIds.size}`);
  lines.push(`- Errors: ${errors}`);
  lines.push(`- Warnings: ${warnings}`);
  lines.push("");

  for (const field of fieldOrder) {
    const issues = byField.get(field);
    if (!issues || issues.length === 0) continue;
    lines.push(`## ${fieldTitles[field]} (${issues.length})`);
    lines.push("");
    for (const issue of issues.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- \`${issue.id}\` (${issue.name}): ${issue.message}`);
    }
    lines.push("");
  }

  if (allIssues.length === 0) {
    lines.push("All records are clean. Nothing to fix.");
    lines.push("");
  }

  writeFileSync(REPORT_PATH, lines.join("\n"), "utf8");
  console.log(
    `[mics:quality] ${rawMics.length} records scanned. ${errors} errors, ${warnings} warnings across ${flaggedIds.size} records.`,
  );
  console.log(`[mics:quality] Report written to ${REPORT_PATH}`);
}

main();
