// Guards the two legal documents mirrored from the Open Mic Explorer app repo
// (vendor/open-mic-explorer/legal/*.md).
//
// These are generated over there and rendered verbatim here, so the failure
// mode this test exists to catch is the app repo regenerating them into a shape
// lib/legal-doc.ts cannot render. Better to fail `npm test` than to ship a
// literal "**" to a store reviewer, and better than the tempting alternative of
// hand-editing a generated agreement on this side.
//
// Run: npm test

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { LEGAL_SLUGS, loadLegalDoc, stripBanner } from "../../lib/legal-doc";

let passed = 0;
const failures: string[] = [];

function assert(cond: boolean, label: string) {
  if (cond) passed += 1;
  else failures.push(label);
}

for (const slug of LEGAL_SLUGS) {
  const path = join(process.cwd(), "vendor", "open-mic-explorer", "legal", `${slug}.md`);
  const raw = readFileSync(path, "utf8");

  // Provenance stays in the repo file. If it is gone, someone hand-edited the
  // document or fetched it from the wrong place.
  assert(
    raw.startsWith("<!--") && raw.includes("Generated by scripts/export-legal.mjs"),
    `${slug}.md is missing its generated-file banner`,
  );
  assert(
    raw.includes("Source of truth:"),
    `${slug}.md banner does not name its source of truth`,
  );

  // ...and never reaches a visitor.
  assert(
    !stripBanner(raw).includes("Do not edit this file directly"),
    `${slug}.md banner is not stripped from the rendered text`,
  );

  // Throws with a file and line if the exporter starts emitting something new.
  let doc: ReturnType<typeof loadLegalDoc> | null = null;
  try {
    doc = loadLegalDoc(slug);
    passed += 1;
  } catch (e) {
    failures.push(`${slug}.md does not parse: ${(e as Error).message}`);
  }

  if (doc) {
    assert(doc.title.length > 0, `${slug}.md has an empty title`);
    assert(doc.body.length > 0, `${slug}.md rendered no body content`);
    assert(
      !doc.body.some((n) => n.kind === "h1"),
      `${slug}.md has a second h1; the page renders exactly one`,
    );

    // Every word in the source, banner aside, has to survive into the render.
    // A silent drop is the one failure a reviewer would notice and we would
    // not.
    const rendered = doc.title +
      " " +
      doc.body
        .map((n) => (n.kind === "ul" ? n.items.join(" ") : n.text))
        .join(" ");
    const sourceWords = stripBanner(raw)
      .replace(/^#{1,2} /gm, "")
      .replace(/^- /gm, "")
      .split(/\s+/)
      .filter(Boolean);
    const renderedWords = rendered.split(/\s+/).filter(Boolean);
    assert(
      sourceWords.length === renderedWords.length,
      `${slug}.md lost content in rendering: ${sourceWords.length} source words, ${renderedWords.length} rendered`,
    );
  }
}

// The contact address in both documents has to be one that exists. There is no
// support@ or legal@ alias on this domain.
for (const slug of LEGAL_SLUGS) {
  const raw = readFileSync(
    join(process.cwd(), "vendor", "open-mic-explorer", "legal", `${slug}.md`),
    "utf8",
  );
  const addresses = raw.match(/[\w.+-]+@stonedgooseproductions\.com/g) ?? [];
  assert(
    addresses.every((a) => a === "kyle@stonedgooseproductions.com"),
    `${slug}.md references an address that does not exist: ${addresses.join(", ")}`,
  );
}

if (failures.length > 0) {
  console.error(`legal-docs test: ${failures.length} failure(s):`);
  for (const f of failures) console.error(`  ✗ ${f}`);
  process.exit(1);
}
console.log(`legal-docs test: all ${passed} assertions passed.`);
